name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 22 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Buenos_Aires
          base: header, activity
          base_hireable: yes
          plugin_isocalendar: yes
